hash-format = "sha256"

[[files]]
file = "config/fancymenu/config.txt"
hash = "6f7a2f977b7f6e570d67ef60f2a5a6a898c0e443d0813d29d040b8727287debc"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "6f839fad9a09709e9c2d1b269218da6a515ea31495575de5bdbc901147740327"

[[files]]
file = "config/fancymenu/customization/GosolMenu.txt"
hash = "8de59169aff876c39bfd5ca9a04cf08d6bb63396e3b590dd0b2ec9255cbef790"

[[files]]
file = "config/fancymenu/menu_identifiers.db"
hash = "2e4d40478c0f21c12c3b1065659ef05c592deee93982ec4abac611145be09468"

[[files]]
file = "config/fancymenu/panoramas/panoramagosol/panorama/panorama_0.png"
hash = "a42e76a0c72453443be61828838ca468a4e145e30df8292058ebafc1b2eb07d9"

[[files]]
file = "config/fancymenu/panoramas/panoramagosol/panorama/panorama_1.png"
hash = "a0cf82d267991f8abec1c13727f5ac2e3e6cd319268cbdbe7e57e3d8f1bdeb22"

[[files]]
file = "config/fancymenu/panoramas/panoramagosol/panorama/panorama_2.png"
hash = "2c09737a3d8d29ac0a994979fa258405905bd37f2b385172d297826b62485a57"

[[files]]
file = "config/fancymenu/panoramas/panoramagosol/panorama/panorama_3.png"
hash = "babfd3219ed90ac894961128b32d9e02f6bafc1d4076155acc53f0f94d933b6e"

[[files]]
file = "config/fancymenu/panoramas/panoramagosol/panorama/panorama_4.png"
hash = "44a7af99e7551a83c482dadf9c0d6c05a37ceb3bcd7fe3239084a41505ab287a"

[[files]]
file = "config/fancymenu/panoramas/panoramagosol/panorama/panorama_5.png"
hash = "a565d85a2aef35b3313de410aaaab81c0c65dd31b3961a55620c95d6618c61a6"

[[files]]
file = "config/fancymenu/panoramas/panoramagosol/properties.txt"
hash = "518f0400e408a61f472db726e0838088d55552b2c2fe153c520ff4266046e16e"

[[files]]
file = "config/fancymenu/splash.txt"
hash = "b63d0357079b14eda545cf8b58b68cb3d24fba97132d547b368a63b7a7e4a9ab"

[[files]]
file = "mods/bfapi.toml"
hash = "5c153556c27a774ae8aeb6e747ebddd3f95bd27349b08f03f766c2f6481eb1e0"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "1c06a6c80fc3898ca68ed742af73dafc8f2f5582a4463728ce94b01f553ab8da"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "62561e1979c26e90a8e60b5d2320879c56a0e3904dd48bed929890dd3cbdf2bc"
metafile = true

[[files]]
file = "mods/dark-loading-screen.toml"
hash = "a7129404822518447540c087931a3b208024badcef8dc2bad430753eac66edc6"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "0079c91da26e7f8937b093abbea5bf69639b588219611e7cadeeb98989bd3c93"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "7de350a9e425dd89b8bb42d2232ff6a10c4affe48c9de6004d5e7094f9d7fa8a"
metafile = true

[[files]]
file = "mods/fabricsit.toml"
hash = "dabac27b3ae32db70ec9a2dec64707e851263a712d1ed0d03853c5dd3949f22f"
metafile = true

[[files]]
file = "mods/fancymenu-fabric.toml"
hash = "d2b4d7ae83e8c548d641de5dccfb583a7a234e129821a19f25674981c3d6d87b"
metafile = true

[[files]]
file = "mods/immersive-portals-mod.toml"
hash = "690222e4c04adb4c63aa3a83cb786c8056035ff57a3c6e5998fb80b0fcd4f2d1"
metafile = true

[[files]]
file = "mods/irisshaders.toml"
hash = "f7ebdb13532e22b8a2ca3424ffc61916749f21be4f8a4ab45b001e4093963cb4"
metafile = true

[[files]]
file = "mods/konkrete-fabric.toml"
hash = "6a6f960f7618742f91e8ee01e0f3444d098383ac846d7f62c58ddfb943b86948"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "c34030a9e1260bbb1a8173d743ff0d0bd83190d33e5ce5525e48b39a66119437"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "adfc60699a9100f1b15850c98c05f7d3df4192c7a7ffcef377047d11fbc9d177"
metafile = true

[[files]]
file = "mods/ok-zoomer.toml"
hash = "988eb2f46a1adfd2692cc4d779ab210b1bfbb2b08d9b5d763fb607ea0171e239"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "77fed5c6646ab89a8c548eb44e957f4ffb2b59d7b0fcf02470942c5ba2ea3d1f"
metafile = true

[[files]]
file = "mods/simple-voice-chat.toml"
hash = "5cca0414a7bc523e68acc708e5659e5345e647193ab84057cd15cebcef538303"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "823cf2b40b652b310a3b179ed0f58afd66b94d76b75f6b9f7adcf02fd6620577"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.toml"
hash = "22757eb3bfdeeeb82605b3512bd0911dc1e07a68e19192f02dff1dbb58bedcb3"
metafile = true
