name = "GosolCraft"
author = "guineu"
version = "2.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14c3b08568e6568fd92d35d0f949c1fc02449ae0319a6ff74a5c3972bb5c55ce"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
