name = "GosolCraft Next"
author = "guineu"
version = "1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
<<<<<<< HEAD
hash = "c5ccdb273bbc4c4fd8821249030ad8aa1f73e9531ac0fbe3c9a8d26c5acfdea8"
=======
hash = "d437cde844ba1c81b96c3b35a2410b1aab4deec5a32be4dcc6f126ab625a0373"
>>>>>>> 0102699 (update tes)

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
